### ISSUE TITLE
Resource coverage report on Puppet 4.x

### ISSUE THREAD

**Issue by bodgit** [rodjek/rspec-puppet#396] opened 2016-07-19 09:14 UTC
The resource coverage report is behaving weirdly when I test with Puppet 4.x.

With defined types, (`foo::*`), rspec-puppet doesn't report them as untouched if I don't add expectations for them, i.e. `it { should contain_foo__bar('test') }`, nor does it error that they don't exist if I _do_ add some, they seem to be in some sort of limbo where the expectations can find them in the catalog if tested against but they're not reported as untouched if not.

If I move back to Puppet 3.x then everything works properly.

**Comment by traylenator** [comment] 2017-03-03 13:56
+1

**Comment by rodjek** [comment] 2017-04-05 03:35
@bodgit or @traylenator, can you provide a more detailed example of this that I can use to reproduce this behaviour?

**Comment by DavidS** [comment] 2017-06-02 12:09
I've put up an example at https://github.com/DavidS/rspec-puppet/commit/5e2f212ae306ac58df74a671ee282d0037850126 that does not work as I would have expected it. 

@bodgit @traylenator : does that look like the issues you've been experiencing?

@rodjek : is my example sensible?

**Comment by rodjek** [comment] 2017-06-05 07:33
@DavidS Unfortunately your test case isn't valid (the examples were missing their expectations). Fixing that and changing the title value to not clash with `Notify[test]` in `Node[default]`

```diff
diff --git a/spec/defines/defines_simple_spec.rb b/spec/defines/defines_simple_spec.rb
index 0a6a0c2..188231f 100644
--- a/spec/defines/defines_simple_spec.rb
+++ b/spec/defines/defines_simple_spec.rb
@@ -1,7 +1,7 @@
 require 'spec_helper'
 
 describe "defines::simple" do
-  let(:title) { 'test' }
-  it { contain_defines__simple("test") }
-  it { contain_notify("test") }
+  let(:title) { 'test12345' }
+  it { is_expected.to contain_defines__simple("test12345") }
+  it { is_expected.to contain_notify("test12345") }
 end
```
gives the expected result (only 1 touched resource because the item being tested `Defines::Simple[test12345]` shouldn't be part of the coverage report)
```
asmodean :0: code/rspec-puppet git:(davids/coverage-define-example)!» bundle exec rspec spec/defines/defines_simple_spec.rb

defines::simple
  should contain Defines::Simple[test12345]
  should contain Notify[test12345]

Total resources:   1
Touched resources: 1
Resource coverage: 100.00%

Finished in 0.16968 seconds (files took 0.98994 seconds to load)
2 examples, 0 failures
```

The opening message made it sound like defined types aren't part of the coverage report at all, which i'm unable to reproduce. Putting your defined type in a wrapper class and then testing that class:
```puppet
class defines::wrapper {
  defines::simple { 'test12345': }
}
```
```ruby
require 'spec_helper'

describe 'defines::wrapper' do
  it { is_expected.to compile }
end
```
```
asmodean :0: code/rspec-puppet git:(davids/coverage-define-example)!» bundle exec rspec spec/classes/defines_wrapper_spec.rb 

defines::wrapper
  should compile into a catalogue without dependency cycles

Total resources:   2
Touched resources: 0
Resource coverage:  0.00%
Untouched resources:

  Defines::Simple[test12345]
  Notify[test12345]

Finished in 0.20661 seconds (files took 0.99059 seconds to load)
1 example, 0 failures
```
shows the defined type as an untouched resource as expected.

**Comment by DavidS** [comment] 2017-06-05 08:19
Yeah, that makes sense. Even adding the component expectations to the class case leads to a valid coverage report. My bad!

https://github.com/DavidS/rspec-puppet/commit/148e89732a3ba34f3b0cb990c5fde8d48a8563a1 for reference.


I'll close this then. If any of the original reports can still repro the issue, feel free to re-open, or resubmit with an example!

**Closed by DavidS** 2017-06-05 08:19 UTC
Labels: awaiting feedback
