### ISSUE TITLE
2.6 is pulling the `fqdn` fact from the base OS

### ISSUE THREAD

**Issue by trevor-vaughan** [rodjek/rspec-puppet#549] opened 2017-07-03 18:03 UTC
Since upgrading to the `2.6` release of `rspec-puppet` our tests are now pulling from the base host's `fqdn` (not sure what else at this point) instead of using the `let(:facts)` version of the values.

This is presently breaking most of our test runs.

**Comment by rnelson0** [comment] 2017-07-03 18:31
Given an rspec file like this:
```puppet
  on_supported_os.each do |os, facts|
    next unless facts[:kernel] == 'Linux'
    context "on #{os} " do
      let :facts do
        facts.merge({
          clientcert: 'wiki',
        })
      end

      context 'when using default params' do
        let :params do
          params
        end
```
And a hiera config in `spec/spec_helper.rb` like this:
```
RSpec.configure do |c|
  c.hiera_config = File.expand_path(File.join(__FILE__, '../fixtures/hiera.yaml'))
  default_facts = {
    puppetversion: Puppet.version,
    facterversion: Facter.version
  }
  default_facts.merge!(YAML.load(File.read(File.expand_path('../default_facts.yml', __FILE__)))) if File.exist?(File.expand_path('../default_facts.yml', __FILE__))
  c.default_facts = default_facts
end
```
And a hiera.yaml like this:
```
---
:backends:
  - yaml
:yaml:
  :datadir: './spec/fixtures/hieradata'
:hierarchy:
  - '%{::clientcert}'
  - 'default'
```
And a validation in the class like this:
```puppet
  if($packages == {}) {
    fail('You must provide a hash of packages for wiki implementation.')
  }
  create_resources('package', $packages)
```
Then, I expect class parameters to be looked up from the file `./spec/fixtures/hieradata/wiki.yaml' and my tests to pass, as they do with rspec-puppet <2.6.0. Instead, with rspec-puppet >= 2.6.0, I receive errors like this:
```
     Puppet::PreformattedError:
       Evaluation Error: Error while evaluating a Function Call, You must provide a hash of packages for implementation. at /.../spec/fixtures/modules/X/manifests/init.pp:109:5 on node Y
```
I have pinned my gemfile to rspec-puppet 2.5.x for now: `gem "rspec-puppet", '~> 2.5.0'`

**Comment by trevor-vaughan** [comment] 2017-07-03 18:32
@rodjek Requesting that 2.6.0 be pulled unless this is an easy fix.

**Comment by ekohl** [comment] 2017-07-03 18:34
Given this is breaking tests I believe 2.6.0 should be a 3.0. release instead. 👍 to pulling it if possible.

**Comment by rodjek** [comment] 2017-07-04 00:43
Opened a PR (#550) which I believe will solve this bug (this is an unintended behavior change, hence the 2.6 release rather than 3.x).

**Comment by trevor-vaughan** [comment] 2017-07-04 02:00
@rodjek The patch fixes my issues as well. Looking forward to the new release!

**Comment by rodjek** [comment] 2017-07-04 02:32
Thanks for letting me know @trevor-vaughan, I'll be pushing out a new release later tonight with the fix.

**Comment by rodjek** [comment] 2017-07-04 09:32
2.6.3 has been pushed to rubygems with the fix for this issue

**Closed by rodjek** 2017-07-04 09:32 UTC
