### ISSUE TITLE
puppet 4 unable to test functions with precondition

### ISSUE THREAD

**Issue by jhoblitt** [rodjek/rspec-puppet#282] opened 2015-05-02 23:23 UTC
Attempting to test a function with a `:pre_condition` under puppet 4.0.0 fails looking for the hardwired rb_env directory.

Something along the lines of:

```
  let(:pre_condition) { 'include ::foo' }
  it { should run.with_params() }
```

Will fail with this error:

```
Evaluation Error: Error while evaluating a Function Call, Could not find a directory environment named 'rp_env' anywhere in the path: <foo>/spec. Does the directory exist? at line 1:1
```

**Comment by DavidS** [comment] 2015-06-22 12:17
I've added a test for that https://github.com/DavidS/rspec-puppet/commit/adbd874785113b5808522e11d118e6ecb9e5720f but couldn't reproduce. If you have a (non-)working example, I'd love to see that.

**Comment by jhoblitt** [comment] 2015-06-23 18:00
@DavidS I am able to reproduce the failure with 2.1.0 but it seems to have been fixed in 2.2.0.  Thanks for adding the regression test.

**Comment by jhoblitt** [comment] 2015-06-23 18:26
@DavidS Actually, the problem is still present for me with rspec-puppet 2.2 and puppet 4.1.0.  Is the `subject#call` syntax in the README no longer supported?

Consider:
```
diff --git a/spec/functions/split_spec.rb b/spec/functions/split_spec.rb
index bb43278..9907a92 100644
--- a/spec/functions/split_spec.rb
+++ b/spec/functions/split_spec.rb
@@ -28,4 +28,9 @@ describe 'split' do
     let(:pre_condition) { 'include ::sysctl::common' }
     it { should run.with_params('aoeu', 'o').and_return(['a', 'eu']) }
   end
+
+  context 'after including a class' do
+    let(:pre_condition) { 'include ::sysctl::common' }
+    it { subject.call(['aoeu', 'o']) == ['a', 'eu'] }
+  end
 end

```

```
  1) split after including a class 
     Failure/Error: it { subject.call(['aoeu', 'o']) == ['a', 'eu'] }
     ArgumentError:
       function 'split' called with mis-matched arguments
       expected one of:
         split(String str, String pattern) - arg count {2}
         split(String str, Regexp pattern) - arg count {2}
         split(String str, Type[Regexp] pattern) - arg count {2}
       actual:
         split(Undef{0}) - arg count {0}
     # ./spec/functions/split_spec.rb:34:in `block (3 levels) in <top (required)>'
```

**Comment by DavidS** [comment] 2015-06-24 09:58
I'll have a look at it.

**Comment by jhoblitt** [comment] 2015-06-29 15:57
@DavidS If its helpful, here's an example of the problem manifesting under 2.2.0 in a real module. https://github.com/jenkinsci/puppet-jenkins/pull/324

**Comment by ITler** [comment] 2016-01-06 12:19
I'm facing same issue. Tests suddenly fail (after Christmas holidays). As I didn't run a bundle update explicitly, I can't explain why. According to apt history.log, my system got kernel and linux-libc-dev library upgrade.

**Comment by ITler** [comment] 2016-01-07 10:51
When a function test fails, error output referes to a number of failed examples. This is the exact number of all tests (in all files) that are tested. (Reproducable by un-/commenting any test in any test file). Maybe this info helps.

**Comment by ITler** [comment] 2016-02-11 08:18
I've just upgraded to `2.3.2` and see that error message slightly changed. I'll add full stack trace.

	Failure/Error: should run.with_params('foo').and_return({
	 Puppet::PreformattedError:
	   Evaluation Error: Error while evaluating a Function Call, undefined method `environment_data_provider' for nil:NilClass at line 1:1
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/data_providers/lookup_adapter.rb:230:in `initialize_env_provider'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/data_providers/lookup_adapter.rb:186:in `env_provider'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/data_providers/lookup_adapter.rb:93:in `lookup_in_environment'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/data_providers/lookup_adapter.rb:178:in `block (2 levels) in env_lookup_options'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/pops/merge_strategy.rb:115:in `block (2 levels) in merge_lookup'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/pops/merge_strategy.rb:114:in `catch'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/pops/merge_strategy.rb:114:in `block in merge_lookup'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/pops/merge_strategy.rb:112:in `each'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/pops/merge_strategy.rb:112:in `reduce'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/pops/merge_strategy.rb:112:in `merge_lookup'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/data_providers/lookup_adapter.rb:177:in `block in env_lookup_options'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/data_providers/lookup_adapter.rb:176:in `catch'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/data_providers/lookup_adapter.rb:176:in `env_lookup_options'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/data_providers/lookup_adapter.rb:159:in `retrieve_lookup_options'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/data_providers/lookup_adapter.rb:134:in `lookup_lookup_options'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/data_providers/lookup_adapter.rb:119:in `lookup_merge_options'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/data_providers/lookup_adapter.rb:61:in `lookup'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/pops/lookup.rb:64:in `search_and_merge'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/resource/type.rb:567:in `block in lookup_external_default_for'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/resource/type.rb:567:in `catch'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/resource/type.rb:567:in `lookup_external_default_for'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/resource/type.rb:392:in `block in inject_external_parameters'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/resource/type.rb:388:in `each'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/resource/type.rb:388:in `inject_external_parameters'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/resource/type.rb:361:in `set_resource_parameters'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/resource/type.rb:169:in `evaluate_code'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/resource.rb:84:in `block in evaluate'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/util/profiler.rb:51:in `profile'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/resource.rb:76:in `evaluate'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/resource/type.rb:484:in `evaluate_parent_type'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/resource/type.rb:163:in `evaluate_code'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/resource.rb:84:in `block in evaluate'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/util/profiler.rb:51:in `profile'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/resource.rb:76:in `evaluate'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/resource/type.rb:484:in `evaluate_parent_type'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/resource/type.rb:163:in `evaluate_code'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/resource.rb:84:in `block in evaluate'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/util/profiler.rb:51:in `profile'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/resource.rb:76:in `evaluate'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/compiler.rb:401:in `each'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/compiler.rb:401:in `evaluate_classes'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/functions/include.rb:33:in `block in <top (required)>'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/functions.rb:162:in `block (2 levels) in newfunction'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/util/profiler.rb:51:in `profile'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/functions.rb:155:in `block in newfunction'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/pops/evaluator/runtime3_support.rb:290:in `call_function'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/pops/evaluator/evaluator_impl.rb:840:in `call_function_with_block'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/pops/evaluator/evaluator_impl.rb:820:in `eval_CallNamedFunctionExpression'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/pops/visitor.rb:67:in `visit_this_1'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/pops/evaluator/evaluator_impl.rb:73:in `evaluate'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/pops/evaluator/evaluator_impl.rb:644:in `eval_Program'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/pops/visitor.rb:67:in `visit_this_1'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/pops/evaluator/evaluator_impl.rb:73:in `evaluate'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/pops/parser/evaluating_parser.rb:57:in `evaluate'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/ast/pops_bridge.rb:111:in `evaluate'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/ast.rb:31:in `safeevaluate'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/resource/type.rb:185:in `evaluate_code'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/resource.rb:84:in `block in evaluate'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/util/profiler.rb:51:in `profile'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/resource.rb:76:in `evaluate'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/compiler.rb:638:in `evaluate_main'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/compiler.rb:180:in `block (2 levels) in compile'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/util/profiler.rb:51:in `profile'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/compiler.rb:180:in `block in compile'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/context.rb:65:in `override'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet.rb:240:in `override'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/puppet-4.3.2/lib/puppet/parser/compiler.rb:168:in `compile'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/rspec-puppet-2.3.2/lib/rspec-puppet/example/function_example_group.rb:69:in `build_compiler'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/rspec-puppet-2.3.2/lib/rspec-puppet/example/function_example_group.rb:47:in `compiler'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/rspec-puppet-2.3.2/lib/rspec-puppet/example/function_example_group.rb:31:in `scope'
	 # /home/bjoern/.rvm/gems/ruby-2.2-head/gems/rspec-puppet-2.3.2/lib/rspec-puppet/example/function_example_group.rb:27:in `subject'
	 # ./spec/functions/parse_instance_name_spec.rb:15:in `block (6 levels) in <top (required)>'

**Comment by rodjek** [comment] 2017-03-14 05:48
I've also been unable to reproduce this error. @jhoblitt I pulled down your fork of puppet-jenkins that you linked to and it ran the tests fine, so I'm leaning towards this being an issue with your workstation setup.  This issue is pretty old now, so I'm going to close this issue for now, but if it's still causing you problems on the latest version of rspec-puppet, please feel free to reopen it.

**Closed by rodjek** 2017-03-14 05:48 UTC
Labels: bug
