### ISSUE TITLE
compile.and_raise_error does not fail when no error is raised

### ISSUE THREAD

**Issue by ITler** [rodjek/rspec-puppet#318] opened 2015-09-03 14:56 UTC
I'm using rspec-puppet `2.2.0`  
I would expect a failure when testing, but tests are green.

Testing against...

    # alf.pp
    class alf {

      $foo = bar
      # no error raised here -> this should make the test fail as I want to test for a raised error.
      # fail("foo")
    }

...with that spec

    # alf_spec.rb
    require 'spec_helper'

    describe 'alf', type: 'class' do
      context 'with defaults for all parameters' do
        it { should compile.and_raise_error(/foo/) }

      end
    end

`.and_raise_error` will only lead to a failing test, if a function `fail('foo')` is defined, but the message is not matching (like `should compile.and_raise_error(/bar/)`).

**Comment by DavidS** [comment] 2015-09-04 07:53
Exactly this case is covered by https://github.com/rodjek/rspec-puppet/blob/master/spec/classes/test_fail_spec.rb which seems to work just fine. Please investigate what is different between those two test cases, maybe that brings insight into what's going wrong here?

**Comment by ITler** [comment] 2015-09-07 07:06
We got a misunderstanding here. Of cause, the test case you've referenced works, but this is not the case I've described. Please see my example again
I would have expected 
* `compile`: yes, (green)
* `and_raise_error(/foo/)`: fail, (red) 
as there is no `fail` within the puppet manifest.

**Comment by DavidS** [comment] 2015-09-07 12:05
Thank you for explaining that. I still have troubles reproducing it though: I've added more tests to this, trying to cover both the compile-does-not-fail and the compile-fails-with-different-mesage case: https://github.com/rodjek/rspec-puppet/compare/master...DavidS:compile-and-raise-error-testing All of those tests succeed for me.

**Comment by DavidS** [comment] 2015-09-07 12:08
Could this be a fix for you: https://github.com/rodjek/rspec-puppet/commit/185e0de8772c41397f142f0ce223d78fc4912675 ?

**Comment by ITler** [comment] 2015-09-07 12:26
When adding `it { expect { should compile.and_raise_error(/foo/) }.to raise_error RSpec::Expectations::ExpectationNotMetError }` to my spec, a test failure is reported, that nothing was raised even when calling _fail_ in a manifest. Nevertheless 185e0de8772c41397f142f0ce223d78fc4912675 is looking really good. (I'm not a ruby professional (,yet)).

**Comment by ITler** [comment] 2015-09-15 14:45
You need more feedback? Do I have to switch the issue's label somehow?

**Comment by DavidS** [comment] 2015-09-15 14:47
Sorry, that slipped through the cracks. The commit seems to clear your issue? So we can either keep this open as a reminder that rspec-puppet should see a new release soon, or close it, as it is already addressed in master.

**Comment by ITler** [comment] 2015-09-16 08:21
Yes. I think, 185e0de could help. Would be good, to get this to a new release.
I would leave this issue open to indicate, that this issue is not resolved for end-user. (After releasing a new version containing the commit, I'll verify that testing works as desired. If it does, I'll close this issue.)

**Comment by DavidS** [comment] 2015-09-16 11:55
agreed, and thanks!

**Comment by mgriffin13** [comment] 2015-09-23 22:08
I'm having a similar issue, where my module code:

```ruby
# alf.pp
class alf {
  $foo = bar

  fail("baz")
}
```
and rspec code
```ruby
# alf_spec.rb
require 'spec_helper'

describe 'alf' do

  context 'with expect and raise' do
    it do
      expect {
        should compile
      }.to raise_error(Puppet::Error, /baz/)
    end
  end
end
```
gives me a test failure:

```
Failures:

  1) alf with expect and raise
     Failure/Error: expect {
       expected Puppet::Error with message matching /baz/, got #<RSpec::Expectations::ExpectationNotMetError: error during compilation: baz 
     # ./spec/classes/alf_spec.rb:8

Finished in 0.35361 seconds
1 example, 1 failure
```

I pulled down the current master branch for the gem, which includes the https://github.com/rodjek/rspec-puppet/commit/185e0de8772c41397f142f0ce223d78fc4912675 commit.

This rspec test successfully evaluates using ```rspec-puppet-1.0.1```

**Comment by DavidS** [comment] 2015-09-28 09:23
@mgriffin13 that's because `should compile` will raise a `RSpec::Expectations::ExpectationNotMetError` indicating - to rspec - that the `alf` class didn't compile. To check for the actual error, you need to `is_expected.to compile.and_raise(Puppet::Error, /baz/)`

**Comment by mgriffin13** [comment] 2015-09-28 14:58
@DavidS thank you. for completeness, here is my new test that passes with the released 2.2.0 gem

```ruby
# alf_spec.rb
require 'spec_helper'

describe 'alf' do

  context 'with expect and raise' do
    it do
      expect {
        is_expected.to compile.and_raise(Puppet::Error, /baz/)
      }
    end
  end
end
```

**Comment by DavidS** [comment] 2015-09-28 15:16
You can even remove the `expect{}` part and just leave it's body. See https://github.com/rodjek/rspec-puppet/blob/master/spec/classes/test_compile_error_spec.rb

**Comment by DavidS** [comment] 2015-12-14 16:50
Closing this in preparation of 2.3.0

**Closed by DavidS** 2015-12-14 16:50 UTC
Labels: bug
