### ISSUE TITLE
TypeError failure with Puppet 5.3.4

### ISSUE THREAD

**Issue by fatmcgav** [rodjek/rspec-puppet#647] opened 2018-02-06 10:17 UTC
As reported in https://tickets.puppetlabs.com/browse/PUP-8418, the latest Puppet 5.3.4 release appears to break under rspec-puppet. 

Stack trace taken from above bug ref:
```

TypeError:
--
no implicit conversion of nil into String
# /usr/local/bundle/gems/puppet-5.3.4/lib/puppet/module.rb:316:in `join'
# /usr/local/bundle/gems/puppet-5.3.4/lib/puppet/module.rb:316:in `has_translations?'
# /usr/local/bundle/gems/puppet-5.3.4/lib/puppet/gettext/module_translations.rb:12:in `block in load_from_modulepath'
# /usr/local/bundle/gems/puppet-5.3.4/lib/puppet/gettext/module_translations.rb:11:in `each'
# /usr/local/bundle/gems/puppet-5.3.4/lib/puppet/gettext/module_translations.rb:11:in `load_from_modulepath'
# /usr/local/bundle/gems/puppet-5.3.4/lib/puppet/node/environment.rb:444:in `use_text_domain'
# /usr/local/bundle/gems/puppet-5.3.4/lib/puppet/indirector/catalog/compiler.rb:52:in `find'
# /usr/local/bundle/gems/puppet-5.3.4/lib/puppet/indirector/indirection.rb:198:in `find'
# /usr/local/bundle/gems/rspec-puppet-2.6.9/lib/rspec-puppet/adapters.rb:83:in `catalog'
# /usr/local/bundle/gems/rspec-puppet-2.6.9/lib/rspec-puppet/adapters.rb:161:in `catalog'
# /usr/local/bundle/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:354:in `build_catalog_without_cache'
# /usr/local/bundle/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:375:in `block in build_catalog'
# /usr/local/bundle/gems/rspec-puppet-2.6.9/lib/rspec-puppet/cache.rb:17:in `call'
# /usr/local/bundle/gems/rspec-puppet-2.6.9/lib/rspec-puppet/cache.rb:17:in `get'
# /usr/local/bundle/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:374:in `build_catalog'
# /usr/local/bundle/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:75:in `block in load_catalogue'
# /usr/local/bundle/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:319:in `with_vardir'
# /usr/local/bundle/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:69:in `load_catalogue'
# /usr/local/bundle/gems/rspec-puppet-2.6.9/lib/rspec-puppet/example/class_example_group.rb:7:in `catalogue'
# /usr/local/bundle/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:10:in `block in subject'
# /usr/local/bundle/gems/rspec-puppet-2.6.9/lib/rspec-puppet/matchers/compile.rb:23:in `call'
# /usr/local/bundle/gems/rspec-puppet-2.6.9/lib/rspec-puppet/matchers/compile.rb:23:in `matches?'
# ./spec/classes/init_spec.rb:33:in `block (3 levels) in <top (required)>'

```

**Comment by dsavell** [comment] 2018-02-06 15:55
+1 For fix, failing on all tests.

**Comment by t0mm13** [comment] 2018-02-08 12:03
uh, is title version meant to match description version ?

**Comment by fatmcgav** [comment] 2018-02-08 12:16
@t0mm13 Heh, good spot... Fixed...

**Comment by t0mm13** [comment] 2018-02-08 12:28
No worries

**Comment by joshcooper** [comment] 2018-02-12 07:18
I believe the root cause is due to `gettext-setup` causing `FastGettext.default_locale` to return nil, which [breaks `puppet`](https://tickets.puppetlabs.com/browse/PUP-8418?focusedCommentId=529687&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-529687).

I've [filed a PR](https://github.com/puppetlabs/gettext-setup-gem/pull/63) against the `gettext-setup-gem` project and verified a few different modules pass rspec tests using puppet 5.3.4, e.g. https://github.com/opus-codium/puppet-dehydrated, https://github.com/puppetlabs/puppetlabs-apt, and https://github.com/puppetlabs/puppetlabs-apache.

Feel free to give the PR a try by temporarily adding the following to your modules' Gemfile:

```
gem 'gettext-setup', github: 'joshcooper/gettext-setup-gem', branch: 'handle-nil-union'
```

While the main issue should be fixed in `gettext-setup`, there are a few other improvements we need to make in `puppet` to prevent older versions of `gettext-setup` from breaking us.

**Comment by rodjek** [comment] 2018-02-27 06:37
Thanks @joshcooper! I'm going to close this issue out as it doesn't look like we need to change anything in rspec-puppet.

**Closed by rodjek** 2018-02-27 06:37 UTC
Labels: bug

**Comment by joshcooper** [comment] 2018-02-27 18:03
Thanks @rodjek. Following up to my earlier comment, https://rubygems.org/gems/gettext-setup/versions/0.30 contains the above fix.
