### ISSUE TITLE
let(:facts) does not populate $facts hash

### ISSUE THREAD

**Issue by daenney** [rodjek/rspec-puppet#344] opened 2016-01-05 13:29 UTC
When doing a `let(:facts) {{ :osfamily => 'Debian' }}` you can the correctly reach `$::osfamily` from top scope or `$osfamily` from local scope in your manifests (as long as it isn't shadowed).

However Puppet 3 introduced the `$facts` hash that is enabled by default in Puppet 4 but that hash does not get populated using the `let(:facts)` statement. This is a problem since any module relying on that will have a bad time during testing unless you work around it with a `let(:pre_condition)`.

Using `$facts` over `$::fact` has a great benefit with strict_variables enabled as accessing `$::fact` will throw a compile error when it doesn't exist whereas `$facts['fact']` will not as it's a key lookup in a hash which will just return nil/undef for a non-existent key.

**Comment by ajf** [comment] 2017-02-03 07:04
@daenney What's this workaround?

```ruby
let(:facts) do
  { "blah" => "blah" }
end

let(:pre_condition) do
  "$facts = #{facts}"
end
```

doesn't seem to do anything (doesn't fail, either)

**Comment by domcleal** [comment] 2017-02-20 10:04
d0d5dd6 (in 2.3.0 or higher) contains tests that check this and they're passing fine on a range of Puppet versions.

I'm also unable to reproduce it on rspec-puppet 2.5.0 with Puppet 4.8, so I'd suggest closing it.

**Closed** 2017-02-20 10:22 UTC
Labels: bug

**Comment by kjetilho** [comment] 2017-10-17 12:01
Is this really the suggested workaround?  That is, adding `"$facts = #{facts}"` to pre_condition?

Complete example:

```ruby
require 'puppetlabs_spec_helper/module_spec_helper'

describe 'foo' do
  let(:facts) do {'command' => 'echo 1-2-3'} end
  let(:pre_condition) {
    [
      "$facts = #{facts}",
      <<-'CODE'
      class foo {
        exec { $facts["command"]: }
        Exec[$::command] { path => "/bin" }
      }
      CODE
    ]
  }

  context "test" do
    it { should compile.with_all_deps }
    it { should contain_exec('echo 1-2-3')
                  .with_path('/bin')
    }
  end
end

```
This works, but it fails in Puppet 4 with `Attempt to assign to a reserved variable name: '$facts'`.  Also a bit inconvenient that it requires :facts to be set explicitly in each example, `facts` is not set to RSpec.configuration.default_facts in this context.

**Comment by kjetilho** [comment] 2017-10-17 15:38
Okay, delving deeper into this, the suggested workaround doesn't work when the facts are non-trivial (e.g., coming from rspec-puppet-facts).  The Ruby inspect format is not valid Puppet DSL when the keys to the hash are symbols (`:os`), so the error "Syntax error at ':' at line 2:12" is given.

In fact I may be barking up the wrong tree here, because if I explicitly enable trusted_node_data in spec_helper,

```ruby
RSpec.configure do |c|
  c.trusted_node_data = true
end
```

I get a different error: `Attempt to assign to a reserved variable name: 'trusted'`

My testing is done in Puppet 3.8.7 with 
  rspec (3.6.0)
  rspec-core (3.6.0)
  rspec-expectations (3.6.0)
  rspec-mocks (3.6.0)
  rspec-puppet (2.6.9)
  rspec-puppet-facts (1.8.0)
  rspec-support (3.6.0)

**Comment by kjetilho** [comment] 2017-10-18 14:15
Haha, hopefully my ramblings can be helpful to someone else.  The assignment to `trusted` was my own code messing up.  So it all works correctly.

(It would be nice if rspec-puppet picked up settings from environment.conf, but that is food for a separate issue.)
