### ISSUE TITLE
manifest is ignored if module_path is specified

### ISSUE THREAD

**Issue by mjs510** [rodjek/rspec-puppet#234] opened 2014-11-14 12:04 UTC
If I do the following in my spec_helper.rb:

RSpec.configure do |c|
  c.manifest= 'spec/site.pp'
end

then my spec/site.pp is run as expected.

However, if I also specify a module path as follows:

RSpec.configure do |c|
  c.module_path = '/path/to/modules'
  c.manifest= 'spec/site.pp'
end

then the spec/site.pp manifest no longer runs. It does  not  seem to matter what module_path is set to. As long as module_path is set, the manifest no longer runs.

Note that the same applies to the default site.pp that is created in  spec/fixtures/manifests. This runs as long as module_path is not specified, otherwise it is ignored. You can test this by putting content within this file eg invalid syntax that should cause an error.

**Comment by Xylakant** [comment] 2015-02-18 15:49
I'm able to reproduce this. The issue occurs if the module_path is set to a directory that does not exist is set to a list of directories separated by a colon. The culprit is https://github.com/rodjek/rspec-puppet/blob/master/lib/rspec-puppet/support.rb#L43 where rspec-puppet checks that the modulepath exists before importing the manifest. I'd expect it to check that the manifestdir exists.

**Comment by DavidS** [comment] 2015-06-30 16:33
#223 was merged in #305 and is now available on master. It'd be great if you could try wether that really fixed your problem.

**Comment by rodjek** [comment] 2017-03-31 00:41
Closing due to inactivity

**Closed by rodjek** 2017-03-31 00:41 UTC
Labels: bug
