### ISSUE TITLE
Regression since rspec-puppet 2.4.0

### ISSUE THREAD

**Issue by alexjfisher** [rodjek/rspec-puppet#417] opened 2016-09-27 23:57 UTC
I've got a test that should fail (and does fail with rspec-puppet 2.4.0) but passes with latest rspec-puppet master. See https://github.com/voxpupuli/puppet-staging/pull/113 for the real world example.

For some reason the `defined` function behaves differently??
Take for example the following code...

``` puppet
$dir='/tmp/test'
$same_dir='/tmp/test/'

file {$dir:
  ensure => directory
}

if !defined(File[$same_dir]) {
  file { $same_dir:
    ensure => directory
  }
}
```

```
Error: Cannot alias File[/tmp/test/] to ["/tmp/test"] at /home/alex/test.pp:9; resource ["File", "/tmp/test"] already declared at /home/alex/test.pp:4
```

This code fails when using puppet apply, but passes if run via latest git rspec-puppet.

**Comment by alexjfisher** [comment] 2016-09-28 09:31
The commit that causes the regression is https://github.com/rodjek/rspec-puppet/commit/d351413ce5c8757fcdd4f69db0e0d89a9cf88c82
@domcleal Thanks for helping me track this down.

**Comment by domcleal** [comment] 2016-09-28 09:46
This is tricky, it looks like this is a behaviour change in Puppet when app_management is enabled. If you set `[main]\n app_management = true` in puppet.conf with the above test file, run it with apply, it compiles and executes without error.

d351413 enables app management by default on Puppet 4.3 and higher, so you get the behaviour change where calling defined() on the file alias seems to now return true. I can't seem to reproduce this for explicit aliases on other types, perhaps it's limited to this automatic alias on the file resource?

**Comment by hlindberg** [comment] 2016-09-28 15:10
Seems like it should be possible to reproduce the problem with a puppet master compile - if that shows the problem please log a PUP issue.

**Comment by alexjfisher** [comment] 2016-09-28 15:11
@hlindberg Yes, I can now reproduce outside of puppet rspec-puppet.  I'll log a new issue.

**Comment by alexjfisher** [comment] 2016-09-28 15:27
@hlindberg https://tickets.puppetlabs.com/browse/PUP-6752  (sorry about the naff title!)

**Comment by rodjek** [comment] 2017-03-09 04:12
I'm going to close this out as the problem is/was in Puppet.

**Closed by rodjek** 2017-03-09 04:12 UTC
