### ISSUE TITLE
Require as Resource Attribute Failing

### ISSUE THREAD

**Issue by jcitarello** [rodjek/rspec-puppet#664] opened 2018-03-15 17:01 UTC
This one's driving me batty!  I found some documentation that mentioned adding a "pre-condition" statement to the rspec file, but that made no difference in the error.  

Where am I going wrong with the require statement? The notify seems to work just fine in rspec, but the requires are failing in rspec in every context they are being used.

<----CODE SNIPPET FROM CLASS HP_UDAGENT::INSTALL---_>
        exec{'hp_udagent_install':
            command => $command,
            cwd     => $install_root,
            path    => '/usr/bin:/usr/sbin:/usr/local/bin:/sbin:/usr/contrib/bin:/usr/lpp/HP',
            require => Class['hp_udagent::extract'],
            notify  => [ Class['hp_udagent::cleanup'], Class['hp_udagent::service'] ],
<----CODE SNIPPET ---_>

<----RSPEC FROM install_spec.rb--->
     Failure/Error:
     	  it { is_expected.to contain_exec('hp_udagent_install').with({
           'command' => '/usr/lpp/HP/agentupgrade.sh --upgrade /usr/lpp/HP/hp-ud-agent-aix-ppc.bff',
           'cwd'     => '/usr/lpp/HP',
           'path'    => '/usr/bin:/usr/sbin:/usr/local/bin:/sbin:/usr/contrib/bin:/usr/lpp/HP',
       'require' => 'Class[Hp_udagent::Extract]',
           'notify'  => '[ Class[Hp_udagent::Cleanup], Class[Hp_udagent::Service] ]',
         })}     
<----RSPEC FROM install_spec.rb--->

     Puppet::Error:
       Could not find resource 'Class[Hp_udagent::Extract]' in parameter 'require' at /home/jcitarello/Projects/modules/hp_udagent/spec/fixtures/modules/hp_udagent/manifests/install.pp:34 on node jcitarello-lin.ercot.com

**Comment by rodjek** [comment] 2018-05-14 02:54
Without a more complete example, I'm going to assume this is a duplicate of the issue you raised in #668 (and the same fix I mentioned there should apply).

**Closed by rodjek** 2018-05-14 02:54 UTC
Labels: duplicate
